# Generated by Django 3.0.3 on 2020-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
