# Generated by Django 3.0.3 on 2020-02-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200226_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItems',
            new_name='ListM',
        ),
    ]
