# Generated by Django 3.0.3 on 2020-02-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20200226_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='listm',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listm',
            name='is_time_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listm',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
