# Generated by Django 3.0.3 on 2020-02-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200226_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listm',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
