# Generated by Django 3.0.3 on 2020-02-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20200226_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='listm',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
