# Generated by Django 3.0.3 on 2020-03-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_listm_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='listm',
            name='is_checklist',
            field=models.BooleanField(default=True),
        ),
    ]
