# Generated by Django 3.0.3 on 2020-02-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
